site_name: python-oxmsg

copyright: |
  &copy; 2024 Steve Canny

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/scanny/python-oxmsg

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - index.md
  - message.md
  - attachment.md
  - recipient.md
  - properties.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            group_by_category: false
            members_order: source
            show_signature_annotations: true
            show_source: false
            signature_crossrefs: true

theme:
  name: material
  features:
    - navigation.sections
    - toc.integrate
    - search.suggest
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
        primary: teal
        accent: lime
